name: pdf_customizer_app
description: A Flutter app for creating customizable PDF documents with GetX and offline MVC architecture.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  sqflite: ^2.3.2
  path_provider: ^2.1.3
  pdf: ^3.10.8
  shared_preferences: ^2.2.2
  uuid: ^4.4.0
  flutter_staggered_animations: ^1.1.1
  google_fonts: ^6.2.1
  permission_handler: ^11.0.1
  image: ^4.0.17
  path: ^1.9.1
  share_plus: ^7.2.1
  printing: ^5.14.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/
    - assets/images/
    - assets/images/logo.png
    - assets/images/invoice.png
    - assets/images/quote.png
    - assets/images/delivery.png
    - assets/images/business_card.png
    - assets/images/cv.png
    - assets/templates/